import { chromium } from '@playwright/test';
import { EmsApi } from './EmsApi';
import { ApiError } from './http';
import { readE2EApiGuestId, writeE2EApiGuestId } from './auth';
import { newE2EDonor, STRIPE_TEST_CARD } from '../data/e2eDonor';
import { DonatePage } from '../pages/lite/DonatePage';
import { LiteSignInPage } from '../pages/lite/LiteSignInPage';
import { LiteRegisterPage } from '../pages/lite/LiteRegisterPage';
import { OptInsPage } from '../pages/lite/OptInsPage';

/**
 * `checkout()` is the reliable existence probe — verified live 2026-09-16: an unknown guest id
 * 404s there (`code: "notFound"`) but silently returns `[]` from `paymentTransactions()`, so that
 * endpoint can't tell "no payments yet" apart from "no such guest".
 */
async function guestExists(ems: EmsApi, eventId: string, guestId: string): Promise<boolean> {
  try {
    await ems.guests.checkout(eventId, guestId);
    return true;
  } catch (e) {
    if (e instanceof ApiError && e.status === 404) return false;
    throw e;
  }
}

/**
 * Registers a brand-new guest on the E2E event through a real browser and returns its id.
 * Guest creation (`POST lite/v1/events/:id/auth/guests`) requires a `captchaToken` field — a real
 * reCAPTCHA Enterprise token generated by executing Google's JS challenge on the live page —
 * verified live 2026-09-16 by capturing the real request body; there is no pure-API way to obtain
 * one, so this drives the same Donate → sign-in → register → opt-ins flow the e2e specs use,
 * stopping once the guest is created and its card pre-authorised (never places an actual donation).
 */
async function registerFreshApiGuest(): Promise<string> {
  const donor = newE2EDonor();
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    const donate = new DonatePage(page);
    await donate.goto();
    await donate.selectPresetAmount(1000);
    await donate.clickDonate();

    await new LiteSignInPage(page).continueWithEmail(donor.email);
    const register = new LiteRegisterPage(page);
    await register.waitForPage();
    await register.fillDetails(donor);
    await register.fillCard(STRIPE_TEST_CARD, `${donor.firstName} ${donor.lastName}`);
    await register.setCoverProcessingFee(false);
    const guestId = await register.submit();
    await new OptInsPage(page).continueWithDefaults();

    return guestId;
  } finally {
    await browser.close();
  }
}

/**
 * Idempotently ensures a registered, card-pre-authorised guest is available for the pure-API
 * donation tests (`tests/api/donations.api.spec.ts`), which need a real guestId to call
 * `checkin.makeDonation` against. Unlike the ticket/lot/raffle fixtures, a missing guest can't be
 * healed back into existence under its old id — a fresh registration always gets a new
 * server-assigned UUID — so this persists whatever id is currently valid to
 * `playwright/.auth/e2e-api-guest.json` (mirroring how `auth.ts` already threads the EMS token
 * through), which `tests/fixtures.ts`'s `e2eEvent` fixture reads in preference to the static
 * `E2E_API_GUEST_ID` env var. Checked first because it reflects the last known-good id from a
 * previous healing; `envGuestId` is the fallback for a machine that has never healed before.
 */
export async function ensureApiGuest(ems: EmsApi, eventId: string, envGuestId: string): Promise<string> {
  const candidate = readE2EApiGuestId() ?? envGuestId;
  if (await guestExists(ems, eventId, candidate)) {
    return candidate;
  }
  const freshGuestId = await registerFreshApiGuest();
  writeE2EApiGuestId(freshGuestId);
  return freshGuestId;
}
